import {
  AlertTriangle,
  ArrowUpDown,
  Baby,
  Bike,
  Briefcase,
  Car,
  Coffee,
  DoorOpen,
  Droplets,
  Dumbbell,
  FireExtinguisher,
  Flame,
  Gamepad2,
  Home,
  KeyRound,
  LucideIcon,
  Microwave,
  ParkingSquare,
  Refrigerator,
  Shirt,
  ShieldCheck,
  ShoppingBag,
  Sofa,
  Sparkles,
  Table2,
  Thermometer,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  Zap,
} from "lucide-react";

/**
 * Keyed on Guesty's own amenity label strings (verified against the real
 * account's listings) so real amenity data can look them up directly.
 * Anything not covered here falls back to a generic check icon.
 */
export const amenityIconMap: Record<string, LucideIcon> = {
  // Original curated set (still used by any remaining mock data)
  "High-Speed WiFi": Wifi,
  "Air Conditioning": Wind,
  "Fully Equipped Kitchen": UtensilsCrossed,
  "Smart TV": Tv,
  "Washer & Dryer": WashingMachine,
  "Private Parking": Car,
  "Swimming Pool Access": Waves,
  "Gym Access": Dumbbell,
  Balcony: DoorOpen,
  "24/7 Security": ShieldCheck,
  "Elevator Access": ArrowUpDown,
  "Self Check-In": KeyRound,

  // Real Guesty amenity labels
  "Air conditioning": Wind,
  "Board games": Gamepad2,
  "Body soap": Droplets,
  "Cleaning products": Sparkles,
  "Clothing storage": Shirt,
  Coffee,
  "Coffee maker": Coffee,
  Conditioner: Droplets,
  Cookware: UtensilsCrossed,
  Cycling: Bike,
  "Dining table": Table2,
  "Disabled parking spot": ParkingSquare,
  "Dishes and silverware": UtensilsCrossed,
  Dishwasher: Sparkles,
  "EV charger": Zap,
  Elevator: ArrowUpDown,
  "Emergency exit": AlertTriangle,
  Essentials: ShieldCheck,
  "Family/kid friendly": Baby,
  "Fire extinguisher": FireExtinguisher,
  "First aid kit": ShieldCheck,
  "Free parking on premises": Car,
  "Garden or backyard": Home,
  Gym: Dumbbell,
  "Hair dryer": Wind,
  Hangers: Shirt,
  Heating: Thermometer,
  "Hot water": Droplets,
  Internet: Wifi,
  Iron: Shirt,
  Kettle: Coffee,
  Kitchen: UtensilsCrossed,
  "Laptop friendly workspace": Briefcase,
  "Long term stays allowed": Home,
  Microwave,
  "Outdoor pool": Waves,
  "Outdoor seating (furniture)": Sofa,
  Oven: Flame,
  "Patio or balcony": DoorOpen,
  Refrigerator,
  Safe: KeyRound,
  Shampoo: Droplets,
  Shopping: ShoppingBag,
  "Shower gel": Droplets,
  "Smoke detector": AlertTriangle,
  Stove: Flame,
  "Suitable for children (2-12 years)": Baby,
  "Suitable for infants (under 2 years)": Baby,
  "Swimming pool": Waves,
  TV: Tv,
  Toaster: Coffee,
  "Towels provided": Sparkles,
  Washer: WashingMachine,
  "Wine glasses": UtensilsCrossed,
  "Wireless Internet": Wifi,
};
