import {
  Armchair,
  ArrowRight,
  BadgeDollarSign,
  Banknote,
  Bath,
  BedDouble,
  Building2,
  Calendar,
  CalendarOff,
  Car,
  ClipboardList,
  Clock,
  Coffee,
  Compass,
  Eye,
  FileBarChart,
  FileText,
  Flower2,
  Gift,
  Handshake,
  Headset,
  Image as ImageIcon,
  KeyRound,
  Layers,
  Lightbulb,
  LineChart,
  Link2,
  Lock,
  LockKeyhole,
  MapPinned,
  MessageCircle,
  Monitor,
  MonitorSpeaker,
  Palette,
  PanelTop,
  PartyPopper,
  Percent,
  PiggyBank,
  ReceiptText,
  Repeat,
  Route,
  ShieldCheck,
  ShieldOff,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Ticket,
  Timer,
  TrendingUp,
  Tv,
  UtensilsCrossed,
  Users,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { InstagramIcon, LinkedInIcon, TikTokIcon } from "@/components/shared/SocialIcons";

type IconComponent = LucideIcon | React.ComponentType<{ className?: string }>;

/**
 * Content stored in the DB references icons by name (a plain string can't
 * hold a component reference), so every icon-bearing array in the admin CMS
 * resolves through this map. Keep it in sync with whatever icon names the
 * admin's icon picker offers.
 */
export const ICONS: Record<string, IconComponent> = {
  Armchair,
  ArrowRight,
  BadgeDollarSign,
  Banknote,
  Bath,
  BedDouble,
  Building2,
  Calendar,
  CalendarOff,
  Car,
  ClipboardList,
  Clock,
  Coffee,
  Compass,
  Eye,
  FileBarChart,
  FileText,
  Flower2,
  Gift,
  Handshake,
  Headset,
  ImageIcon,
  KeyRound,
  Layers,
  Lightbulb,
  LineChart,
  Link2,
  Lock,
  LockKeyhole,
  MapPinned,
  MessageCircle,
  Monitor,
  MonitorSpeaker,
  Palette,
  PanelTop,
  PartyPopper,
  Percent,
  PiggyBank,
  ReceiptText,
  Repeat,
  Route,
  ShieldCheck,
  ShieldOff,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Ticket,
  Timer,
  TrendingUp,
  Tv,
  UtensilsCrossed,
  Users,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  Instagram: InstagramIcon,
  LinkedIn: LinkedInIcon,
  TikTok: TikTokIcon,
};

export type IconName = keyof typeof ICONS;

export function resolveIcon(name: string): IconComponent {
  return ICONS[name] ?? ShieldCheck;
}
